#!/usr/bin/env groovy

/**
 *  Fixes the source code according the patch generated by WalkMod and pushes it if tests pass
 */
def call(boolean validatePatch = false, String reportDir = 'target', String branch = 'master', String mvnHome = null) {

    if (hasWalkModPatch(mvnHome)){

        if (validatePatch) {
            input "Does the patch look ok?"
        }

        generateWalkModReport reportDir: reportDir

        applyWalkModPatch

        if(mvnHome != null) {
            sh "${mvnHome}/bin/mvn -DskipWalkmod test"
        }

        pushWalkModPatch branch : branch
    }


}
